version: 2
updates:
  - package-ecosystem: npm
    directory: /back
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /front
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
